name: ssnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - matplotlib
  - pandas
  - seaborn
  - pip
  - pip:
    - snntorch
    - wandb