name: rsnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - gymnasium
  - scikit-learn
  - jupyter
  - pytest
  - black
  - flake8
  - pre-commit
  - pip
  - pip:
    - snntorch
    - wandb
    - tqdm
    - ipywidgets
    - tensorboard
    - gym
    - stable-baselines3
    - optuna
    - rich