# Model Configuration
model:
  input_size: 784
  hidden_size: 256
  output_size: 10
  num_steps: 100
  beta: 0.95

# Training Parameters
training:
  epochs: 1
  batch_size: 32
  learning_rate: 0.001
  beta1: 0.9
  beta2: 0.999

# Data Configuration
data_path: "data/"
data:
  train_path: "data/train"
  val_path: "data/val"
  test_path: "data/test"
  encoding_method: "rate"
  time_steps: 100
  augmentation: true

# Logging and Visualization
logging:
  log_dir: "logs/"
  tensorboard: true
  plot_frequency: 5
  save_plots: true
  metrics:
    - accuracy
    - spike_rate
    - membrane_potential

# Hardware
device: "cuda"
num_workers: 4
pin_memory: true

# Random Seed
seed: 42